### ISSUE TITLE
GETTING STARTED

### ISSUE THREAD

**Issue by ryankurte** [Firstyear/kanidm#138]
hey, having a bash at [GETTING_STARTED](https://github.com/Firstyear/kanidm/blob/master/GETTING_STARTED.md) and have a few issues / comments / thoughts. Probably this will be a multi-part saga because i haven't finished yet...

From the getting started notes:

> You should have a ca.pem, cert.pem and key.pem in your kanidmd volume. It's up to you to put them in there some how.

What is the function of these certs / why are they required? (Unclear if this should be a server certificate, what capability constraints are okay etc.)

> You should have a ca.pem, cert.pem and key.pem in your kanidmd volume. It's up to you to put them in there some how.

Might as well provide an instruction here:
```
docker run --rm -it -v kanidmd:/kanidmd -v`pwd`:/work debian cp /work/cert.pem /work/cert.key /work/ca.pem /kanidmd/
```

> Then you can setup the initial admin account and initialise the database into your volume.
You might like to look at [multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/) (and also using [alpine](https://hub.docker.com/_/alpine) as a base) to decrease the image size, also, [rude timezone assumptions](https://github.com/Firstyear/kanidm/blob/516a128c5ff3b43d1c33da7b12b77f18c0543823/kanidmd/Dockerfile#L16)...

> ```
> docker run -p 443:8443 -v /Users/william/development/rsidm/insecure:/data firstyear/kanidmd:latest /home/kanidm/target/release/kanidmd server -D /data/kanidm.db -C /data/ca.pem -c /data/cert.pem -k /data/key.pem --bindaddr 0.0.0.0:8443 --domain localhost
> ```

It might be nice to document the ports / why they're chosen here, also there's absolutely no way you're getting my 443 binding, consider a higher / non-conflicted default? also differs from [here](https://github.com/Firstyear/kanidm/blob/516a128c5ff3b43d1c33da7b12b77f18c0543823/kanidmd/Dockerfile#L4) for little reason afaik?

> For now, the CLI is still from the source 

</3 ... looks like you need libsqlite3-dev installed from somewhere / could be good to document that?

aaand, that's where i'm up to so far

**Comment by Firstyear** [comment]
> hey, having a bash at [GETTING_STARTED](https://github.com/Firstyear/kanidm/blob/master/GETTING_STARTED.md) and have a few issues / comments / thoughts. Probably this will be a multi-part saga because i haven't finished yet...

I know I said it a few times but *thanks* heaps for looking into this, I really appreciate the feedback! 

> 
> From the getting started notes:
> 
> > You should have a ca.pem, cert.pem and key.pem in your kanidmd volume. It's up to you to put them in there some how.
> 
> What is the function of these certs / why are they required? (Unclear if this should be a server certificate, what capability constraints are okay etc.)

Right, this is because of secure_cookies = true in the actix properties. It's so that in the auth init step if you aren't on https you won't send the cookies which means the auth can not progress due to state violations. It's basically to "limit" cred disclosure by forcing you to have https setup. Note that CA validation does NOT affect this, even if you have reqwest set to not verify CA's or hostnames or anything, it doesn't matter, but the connection has to be https else it won't send the cookies.

So what I'll do is I'll probably document this in a "why tls" and link from the doc. Is that a reasonable solution to "why?" here? 

> 
> > You should have a ca.pem, cert.pem and key.pem in your kanidmd volume. It's up to you to put them in there some how.
> 
> Might as well provide an instruction here:
> 
> ```
> docker run --rm -it -v kanidmd:/kanidmd -v`pwd`:/work debian cp /work/cert.pem /work/cert.key /work/ca.pem /kanidmd/
> ```

Yep, good idea. 

> 
> > Then you can setup the initial admin account and initialise the database into your volume.
> > You might like to look at [multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/) (and also using [alpine](https://hub.docker.com/_/alpine) as a base) to decrease the image size, also, [rude timezone assumptions](https://github.com/Firstyear/kanidm/blob/516a128c5ff3b43d1c33da7b12b77f18c0543823/kanidmd/Dockerfile#L16)...
> 

I have a small corporate interest to use suse, they do pay my bills after all. Multistage build is a good idea to look into though, so I should do this. 

> > ```
> > docker run -p 443:8443 -v /Users/william/development/rsidm/insecure:/data firstyear/kanidmd:latest /home/kanidm/target/release/kanidmd server -D /data/kanidm.db -C /data/ca.pem -c /data/cert.pem -k /data/key.pem --bindaddr 0.0.0.0:8443 --domain localhost
> > ```
> 
> It might be nice to document the ports / why they're chosen here, also there's absolutely no way you're getting my 443 binding, consider a higher / non-conflicted default? also differs from [here](https://github.com/Firstyear/kanidm/blob/516a128c5ff3b43d1c33da7b12b77f18c0543823/kanidmd/Dockerfile#L4) for little reason afaik?

Sure, that's fine. 

> 
> > For now, the CLI is still from the source
> 
> </3 ... looks like you need libsqlite3-dev installed from somewhere / could be good to document that?

Uhhhhh it shourdn't be needed? Are you doing a build from the project root or in kanidm_tools? sqlite-devel should only be needed when you build kandimd components, kanidm_tools + kanidm_client don't need it. 


> 
> aaand, that's where i'm up to so far

**Comment by Firstyear** [comment]
going to close this as the issues have been addressed, and I think you have been a bit busy lately, so if you find more, you can open a new issue. Thanks for having a go! :)
